export const elements = {
    connectedLabel: document.querySelector<HTMLElement>("[data-connected-label]"),
    chatMessages: document.querySelector<HTMLElement>("[data-chat-messages]"),
    chatInput: document.querySelector<HTMLInputElement>("[data-chat-input]"),
    chatSendButton: document.querySelector<HTMLButtonElement>("[data-chat-send]"),
    guestLoginButton: document.querySelector<HTMLButtonElement>("[data-guest-login]"),
    logoutButton: document.querySelector<HTMLButtonElement>("[data-logout-button]"),
    currentUserDisplay: document.querySelector<HTMLElement>("[data-current-user]"),
    usersCount: document.querySelector<HTMLElement>("[data-users-count]"),
    usersList: document.querySelector<HTMLElement>("[data-users-list]"),
    mediaInput: document.querySelector<HTMLInputElement>("[data-media-input]"),
    queueNextButton: document.querySelector<HTMLButtonElement>("[data-queue-next]"),
    queueLastButton: document.querySelector<HTMLButtonElement>("[data-queue-last]"),
    currentTitle: document.querySelector<HTMLElement>("[data-current-title]"),
    syncStatus: document.querySelector<HTMLButtonElement>("[data-sync-status]"),
    playlistItems: document.querySelector<HTMLElement>("[data-playlist-items]"),
    playlistCount: document.querySelector<HTMLElement>("[data-playlist-count]"),
    playlistDuration: document.querySelector<HTMLElement>("[data-playlist-duration]"),
    loginModal: document.querySelector<HTMLElement>("[data-login-modal]"),
    loginNameInput: document.getElementById("login-name-input") as HTMLInputElement | null,
    loginPasswordInput: document.getElementById("login-password-input") as HTMLInputElement | null,
    loginSubmitBtn: document.getElementById("login-submit-btn") as HTMLButtonElement | null,
    loginErrorMsg: document.getElementById("login-error-msg") as HTMLElement | null,
};
